name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0  # Adjust the version as needed
      - name: Install dependencies
        run: |
            pwd
#            dotnet restore BlazorApp/BlazorApp.csproj 
      - name: Build Blazor app
        run: ls #dotnet build BlazorApp/BlazorApp.csproj --configuration Release
      - name: Publish to GitHub Pages
        run: dotnet publish BlazorApp/BlazorApp.csproj --configuration Release --output publish
#          dotnet tool install -g dotnet-ef --version 7.0.0
#          dotnet ef database update --project BlazorApp/BlazorApp.csproj --startup-project BlazorApp/BlazorApp.csproj
          

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: BlazorApp/BlazorApp/publish

# You may need additional steps or modifications based on your project setup.
