name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      # Setup .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      
      # Install .NET WASM Build Tools
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
      
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish BlazorApp/BlazorApp.csproj -c:Release -p:GHPages=true -o dist/BlazorApp --nologo
      
      # Commit wwwroot to GitHub Pages
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: dist/BlazorApp/wwwroot